{% set name = "import-linter" %}
{% set version = "2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/import_linter-{{ version }}.tar.gz
  sha256: c6a5057d2dbd32e1854c4d6b60e90dfad459b7ab5356230486d8521f25872963

build:
  entry_points:
    - lint-imports = importlinter.cli:lint_imports_command
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - fastapi
    - uvicorn
    - rich >=14.2.0
    - python >={{ python_min }}
    - click >=6
    - grimp >=3.14
    - tomli >=1.2.1
    - typing-extensions >=3.10.0.0
    - typing_extensions >=3.10.0.0

test:
  imports:
    - importlinter
  commands:
    - pip check
    - lint-imports --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/import-linter/
  summary: Enforces rules for the imports within and between Python packages.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - millsks
    - rxm7706
    - cshaley
