{% set name = "import-linter" %}
{% set version = "2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 393fadb2e91304c22c5ceab575213ed2b6a794abc7bd05ab345f2430930b2eae

build:
  entry_points:
    - lint-imports = importlinter.cli:lint_imports_command
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - pip
  run:
    - python >={{ python_min }}
    - click >=6
    - grimp >=3.2
    - tomli >=1.2.1
    - typing-extensions >=3.10.0.0

test:
  imports:
    - importlinter
  commands:
    - pip check
    - lint-imports --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/import-linter/
  summary: Enforces rules for the imports within and between Python packages.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
